---
- name: checking for agent install
  stat:
    path: /usr/lib/forescout
  register: agent

- debug:
    msg: "forescout agent not found (installing)"
  when: not agent.stat.exists

- debug:
    msg: "forescout agent found (skipping install)"
  when: agent.stat.exists

- name: copying sc.tar.gz to /tmp for install
  get_url:
    url: '{{ redhat_forescout_agent_url }}'
    dest: /tmp/sc.tar.gz
    validate_certs: no
    mode: 0777
  when: not agent.stat.exists

- name: extract sc.tar.gz to /tmp for install
  unarchive:
    src: /tmp/sc.tar.gz
    dest: /tmp/
    remote_src: yes
    mode: 0777
  when: not agent.stat.exists

- name: change shell permissions for install.sh
  file:
    path: /tmp/secure_connector
    state: directory
    recurse: yes
    mode: 0777
  when: not agent.stat.exists

- name: execute install.sh for forescout
  shell:
    cmd: ./install.sh
    chdir: /tmp/secure_connector
  when: not agent.stat.exists

- name: verify forescout started
  shell:
    cmd: ./start_sc_agent.sh
    chdir: '{{ redhat_forescout_agent_path }}'
